### ISSUE TITLE
Typescript typing available

### ISSUE THREAD

**Issue by hoetmaaiers** [vadzim/use-leaflet#67]
Is Typescript typing available? Or is it being worked on? If not I might feel like adding some effort in creating typings.

**Comment by vadzim** [comment]
Hi.
No, there'are no typescript typings available.
It'd be very nice if you are able to provide them)

**Comment by hoetmaaiers** [comment]
Is there interest in converting the code into Typescript? My second option
would be to add type definitions to the project.

I am looking into some time to contribute on this work.

Op di 12 nov. 2019 16:53 schreef Vadzim <notifications@github.com>:

**Comment by vadzim** [comment]
It's nice to have type checking integrated with linter, and afaik this is not available with typescript.

So I'm still not sure if it make sense to convert the whole project. Though I don't have enough experience with typescript projects workflow, publishing etc.
I guess adding typings could be a good step.

**Comment by hoetmaaiers** [comment]
Ok, I will look into it.

**Comment by vadzim** [comment]
closed with ec0064bfe0024c519700e3b28e98fefa9a2f4f3f

**Comment by hoetmaaiers** [comment]
Awesome thanks. I'll throw away what I started working on :P

**Comment by vadzim** [comment]
I would say it could make sense to check one work before throwing away
another ;)

аў, 19 ліс 2019, 11:27 карыстальнік Hoetmaaiers <notifications@github.com>
напісаў:

**Comment by hoetmaaiers** [comment]
Fair point, when this is availlable in the next release I will test it in my production code. Feels like te best approach, my typings work was not that far progressed.

**Comment by vadzim** [comment]
It's published in 1.6.1

**Comment by hoetmaaiers** [comment]
Seems to be typed enough for my use case. Thank you @vadzim .
